---
- name: Configure MariaDB users
  hosts: db_servers
  become: yes

  tasks:
    - name: Create users and set password if not present
      mysql_user:
        name: "{{ item['FIXME'] }}"
        update_password: on_create
        password: "{{ item['FIXME'] }}"
        state: FIXME
      loop: "{{ mysql_user_passwords }}"

    - name: Configure users in MariaDB
      mysql_user:
        name: "{{ item['FIXME'] }}"
        host: "{{ item['FIXME'] }}"
        priv: "{{ item['FIXME'] }}"
        state: "{{ item['FIXME'] }}"
      loop: "{{ mysql_users }}"

    - name: Update missing passwords
      mysql_user:
        name: "{{ item['name'] }}"
        host_all: yes
        update_password: always
        password: "{{ item['password'] }}"
        state: present
      loop: "{{ mysql_user_passwords }}"
